siemens/mtda

.travis.yml
debian/changelog
scripts/check-version

Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>

travis-ci: check if version in debian/changelog matches mtda/__version__

---

mtda-cli
mtda.ini
mtda/client.py
mtda/main.py

Added support for changing the prefix key configuration

Added support for changing the prefix key configuration

---

.travis.yml

Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>

travis-ci: deploy tagged commits to PyPI

---

mtda/power/pduclient.py

Updated Class name based on instantiated value

Updated Class name based on instantiated value

---

configs/qemu.ini
debian/.gitignore
debian/control
debian/rules

Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>

debian: produce a mtda-kvm package

---

README.md

README: add 'CI' badge

---

README.md

README: add a badge for readthedocs.io

---

.github/workflows/main.yml

ci: upload .deb files to gemfury

---

mtda/keyboard/qemu.py

keyboard/qemu: correct check for qemu power controller

---

mtda-cli

mtda-cli: add --help option

---

debian/changelog
mtda/__version__.py

mtda: bump version to 0.13

---

.github/workflows/pypi.yml

ci: build and pyblish to pypi.org

---

mtda-cli

mtda-cli: announce service using zeroconf

---

debian/mtda-config.path
debian/mtda-config.service
debian/rules

make mtda service restart when /etc/mtda/config is changed
This PR closes #36 .
Signed-off-by: bhargavdas <bhargav_das@mentor.com>

debian:restart mtda service when /etc/mtda/config is changed

---

docs/fixtures.rst
docs/index.rst

docs/fixtures: describe USB Functions that may be provided

---

.reuse/dep5

reuse: match all .rst files from docs/

---

debian/changelog
mtda/__version__.py

mtda: bump version to 0.14

---

meta-isar/recipes-python/mtda/mtda_git.bb

meta-isar/recipes-python: pull mtda v0.14

---

kas-container

Update kas-container to the latest one.

kas-container: Update to 2.6.3

---

meta-isar/conf/machine/nanopi-r1.conf
meta-isar/recipes-bsp/firmware-nanopi-r1/firmware-nanopi-r1.bb
meta-isar/recipes-core/images/mtda-image.inc

Testing wifi:
`
sudo nmcli dev wifi connect <ssid name> password <password>`
Testing bluetooth:
```
bluetoothctl
```

Add support for wifi and bluetooth

---

meta-isar/recipes-core/images/mtda-image.inc

Closes: #134 
Signed-off-by: Richa Bharti <Richa_Bharti@mentor.com>

apt: mtda apt link changed

---

mtda-cli

mtda-cli: add missing help options for subcommands

---

mtda/storage/writer.py

storage/writer: handle end of stream for bzip2 streams

---

mtda/client.py
mtda/constants.py
mtda/storage/writer.py

Based on bz2 logic.
Closes: #121

mtda: add support for xz compressed images

---

.github/workflows/main.yml
.github/workflows/pypi.yml

Signed-off-by: bhargavdas <bhargav_das@mentor.com>

ci: build packages when a PR is created

---

.github/workflows/main.yml

ci: push package updates to Gemfury only for release tags

---

meta-isar/recipes-python/mtda/mtda_git.bb

meta-isar/recipes-python: pull mtda version 0.15

---

.github/workflows/main.yml
.github/workflows/pypi.yml

ci: run workflows when version tags are pushed

---

mtda/keyboard/hid.py

Give-up after a second if we cannot write the HID report.
Fixes: #151

keyboard/hid: make write_report() non-blocking

---

kas/debian/mtda-beaglebone-black.yml
meta-isar/conf/machine/beaglebone-black.conf
meta-isar/recipes-bsp/u-boot/u-boot-2021.10.inc
meta-isar/recipes-bsp/u-boot/u-boot-nanopi-r1_2021.10.bb
meta-isar/recipes-bsp/u-boot/u-boot.inc
meta-isar/recipes-kernel/linux/linux-beaglebone-black.bb
meta-isar/scripts/lib/wic/canned-wks/beaglebone-black.wks.in

I haven't tried booting the image just yet

add support for the beaglebone-black

---

kas/common/base.yml
meta-isar/conf/machine/beaglebone-black.conf
meta-isar/conf/machine/nanopi-r1.conf
meta-isar/recipes-crypto/gnutls/gnutls28.bb

Update to the latest ISAR release(v0.8)

kas/common/base.yml: uprev to ISAR v0.8

---

docs/FAQ.rst
docs/index.rst

Add Static IP settings documentation.
Signed-off-by: sarath P T <Sarath_PT@mentor.com>

Static IP settings documentation

---

.github/workflows/main.yml
.github/workflows/pypi.yml
.github/workflows/ubuntu.yml
docs/dev.rst

docs: add rough release process

---

meta-isar/recipes-conf/hostname/files/postinst
meta-isar/recipes-conf/hostname/mtda-hostname_0.4.bb

Signed-off-by: Bhargav Das <bhargav_das@mentor.com>

meta-isar: remove name resolution message during sudo

---

.github/auto_assign.yml
.github/workflows/assign.yml

Closes: #158 
Signed-off-by: Richa Bharti <Richa_Bharti@mentor.com>

ci: auto-assign reviewers when PRs are raised

---

.github/workflows/assign.yml

Signed-off-by: Richa Bharti <Richa_Bharti@mentor.com>

ci: auto assign reviewer on pull_request_target

---

.github/workflows/main.yml

Signed-off-by: Badrikesh Prusty <Badrikesh_Prusty@mentor.com>

ci: fix no files found in the path for upload

---

mtda/constants.py
mtda/main.py
mtda/storage/controller.py
mtda/storage/docker.py
mtda/storage/helpers/image.py
mtda/storage/qemu.py
mtda/storage/samsung.py
mtda/storage/usbf.py

constants: add STORAGE constants

---

tox.ini

tox: add py310 to the list of environments

---

debian/changelog
mtda/__version__.py

debian: open the 0.18 development window

---

Kconfig

Add entry for environment section
Signed-off-by: Vijai Kumar K <vijaikumar.kanagarajan@siemens.com>

Kconfig: add entry for environment section

---

kas-container

Use kas v3.1.
Signed-off-by: Vijai Kumar K <vijaikumar.kanagarajan@siemens.com>

Update to the latest kas

---

debian/rules

debian: install to /usr/lib/pythonX.Y/dist-packages/mtda

---

debian/changelog

debian: prepare changelog for v0.18-1

---

configs/www.conf
debian/mtda.service
debian/rules
docs/build.rst
docs/config.rst
docs/dev.rst
meta-isar/recipes-python/mtda/mtda_git.bb
mtda-cli
mtda-service
mtda/main.py
scripts/test-using-docker
setup.py
tox.ini

mtda-service: move service code from mtda-cli to its own module

---

.github/workflows/main.yml

ci: cache downloads and sstate

---

.reuse/dep5
meta-isar/recipes-conf/network/files/90-systemd-networkd-disabled.preset
meta-isar/recipes-conf/network/mtda-network_0.1.bb
meta-isar/recipes-core/images/mtda-image.bb

For details, see individual commit messages.
cc @bovi

Collection of fixes after transition to bookworm

---

mtda-cli
mtda/client.py
mtda/storage/helpers/image.py

Among others, this fixes correctness issues in the bmap writing code. For details, see the individual commit messages.
@chombourger : feel free to cherry-pick commits in case other changes need more time for discussions.
cc @bovi

correctness and performance fixes for bmap support

---

mtda/client.py
mtda/main.py
mtda/storage/helpers/image.py
mtda/storage/writer.py

For details, please see the individual commit messages.

Various fixes to make mtda more resilient against user and system errors

---

mtda/main.py
mtda/support/usb.py

Fixes around USB gadget mode

---

mtda/templates/index.html

www: show current power state in web-ui

---

mtda-service

Shutdown the service when SIGTERM is received.

chore(service): handle SIGTERM

---

mtda/main.py

main uses many global imports as it is (unfortunately) mixing client-side and service-side code: move many imports into the few methods where they are used.

chore(main): rework global imports

---

docs/usage.rst

Add documentation to use the Assist board as a keyboard to DUT.

chore(docs): Add Keyboard Usage Documentaion

---

.reuse/dep5
kas-container
kas/common/base.lock.yml
kas/common/base.yml
kas/opt/ab-rootfs.lock.yml
kas/opt/ab-rootfs.yml

Along that, we make use of new kas features that simplify the maintenance:
- `kas lock` to manage lockfiles and semi-automate layer updates
- `kas diff` to generate a deep diff of what changed on layer updates

Maintenance: update kas and layers

---

mtda-www
mtda/assets/keyboard.css
mtda/assets/keyboard.js
mtda/templates/index.html

While the browser is able to forward most key events, there are a few keys that the browser may handle internally. By having the virtual keyboard, users hopefully have a work-around to send "special" keys.

feat(www): re-introduce the virtual keyboard

---

mtda/keyboard/controller.py
mtda/keyboard/hid.py
mtda/keyboard/qemu.py
mtda/main.py

fix(keyboard): allow modifier keys for special keys

---

mtda/templates/index.html

Send Ctrl-Alt-Fx via icons placed in the title bar of the video window.
Closes: #504

feat(www): add shortcuts to switch TTYs

---

debian/control
mtda-service
mtda-www
mtda/client.py
mtda/main.py

Prepare for the upgrade to trixie by supporting either Pyro4 (bookworm) or Pyro5 (trixie)

Support for Pyro5

---

mtda-cli
mtda/main.py
mtda/storage/helpers/image.py
mtda/storage/writer.py
mtda/templates/index.html

- make it more linear
- validate last range as well
closes: #501

Storage write improvements
