siemens/mtda

mtda-cli
mtda/client.py
mtda/console/input.py
mtda/main.py

From commit 26bbee6, the atexit based console cleanup incorrectly
restores the terminal to raw mode.
Remove the terminal restore in the main application and move console
init to a separate function. Let the atexit based cleanup routine
restore the correct settings back.

mtda-cli: Fix incorrect terminal restore

---

mtda-cli
mtda/__version__.py
mtda/client.py
mtda/main.py

Right now there is no user friendly way to find out the MTDA
version. Add -v option to print the MTDA version.
Also, add provision to print the host and remote mtda version
part of target info(mtda-cli -r).
Bump the version to 0.5.1. When quering older versions of mtda
server, which doesnot yet have this feature implemented, the
version will be printed as <=0.5.

mtda-cli: Add option to print the MTDA version

---

mtda/main.py

The keyboard_write() function has a parameter named 'str', which
creates conflict with the built-in str() method. So renaming it
to something else solves the following error.
Current Log:
```
mtda@mtda:~$ mtda-cli keyboard write test
Traceback (most recent call last):
File "/usr/bin/mtda-cli", line 767, in <module>
app.main()
File "/usr/bin/mtda-cli", line 753, in main
status = cmds[cmd](stuff)
File "/usr/bin/mtda-cli", line 367, in keyboard_cmd
cmds[cmd](args)
File "/usr/bin/mtda-cli", line 355, in keyboard_write
self.client().keyboard_write(args[0])
File "/usr/lib/python3/dist-packages/mtda/client.py", line 118, in keyboard_write
return self._impl.keyboard_write(data, self._session)
File "/usr/lib/python3/dist-packages/mtda/main.py", line 384, in keyboard_write
self.mtda.debug(3, …
```

mtda/main: rename 'str' keyboard_write() function parameter

---

mtda/main.py

Currently the self._session_timer thread is not stopped while exiting hence the following error is observe while invoking `ctrl+c` 
```
^CException ignored in: <module 'threading' from '/usr/lib/python3.9/threading.py'>
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 1428, in _shutdown
lock.acquire()
KeyboardInterrupt:
```
This PR stops the thread and exits the application without any errors while using `ctrl+c`
I have also added exit message
```
^CExiting, Thank you for using MTDA ...
```
This PR also fixes [https://github.com/siemens/mtda/issues/67](url) partially.

mtda/main: Stop self._session_timer thread before exiting

---

debian/control
docs/config.rst
mtda.ini
mtda/power/usbrelay.py

Add a usbrelay driver to drive relays exposed to the host via a
USB HID interface and the usbrelay tool. The driver expects a list
of relays (lines) to drive.

mtda/power: add support for USB HID relay (usbrelay driver)

---

docs/build.rst
docs/fixtures.rst

The NanoPI NEO image is now based on Debian bullseye.
The block device should be specified in /etc/mtda/usb-functions when
using the usbf storage driver.

docs: minor corrections

---

setup.py

Closes: #132
Signed-off-by: Richa Bharti <Richa_Bharti@mentor.com>

setup.py: needs zeroconf to be installed to run mtda-cli on host

---

setup.py

Fixes the below pycodestyle issue:
setup.py:57:1: E101 indentation contains mixed spaces and tabs
setup.py:57:1: W191 indentation contains tabs

setup.py: replace tab with space

---

mtda/storage/writer.py

storage/writer: fix a variable referenced before use error in write_raw

---

meta-isar/conf/machine/nanopi-r1.conf

Kill a build warning about PREFERRED_PROVIDER_u-boot-nanopi-r1
not being set.
Fixes: #142

meta-isar/conf: set PREFERRED_PROVIDER for u-boot-nanopi-r1

---

mtda/main.py

Starting the agent without a [main] section in the configuration
would cause an exception as the name attribute was only set from
load_main_config()
Fixes: f75ca67

main: make sure the agent is created with a default name

---

meta-isar/conf/machine/nanopi-r1.conf

In 3d6d41d6, we reverted to a version of ISAR that doesnot have the
IMAGE_FSTYPES support.
Fixes wic-img generation in nanopi-r1.

Revert "meta-isar/conf: use IMAGE_FSTYPES instead of IMAGE_TYPE"

---

debian/control
meta-isar/recipes-bsp/u-boot/u-boot-nanopi-r1_2021.10.bb
meta-isar/recipes-python/compression/files/zstandard-0.14.0/debian/changelog
meta-isar/recipes-python/compression/files/zstandard-0.14.0/debian/control
meta-isar/recipes-python/crypto/files/curve25519-donna-1.3/debian/changelog
meta-isar/recipes-python/crypto/files/curve25519-donna-1.3/debian/control
meta-isar/recipes-python/crypto/files/ed25519-1.5/debian/changelog
meta-isar/recipes-python/crypto/files/ed25519-1.5/debian/control
meta-isar/recipes-python/net/files/hap-python-3.0/debian/changelog
meta-isar/recipes-python/net/files/hap-python-3.0/debian/control
meta-isar/recipes-python/net/files/zeroconf-0.28.6/debian/changelog
meta-isar/recipes-python/net/files/zeroconf-0.28.6/debian/control
meta-isar/recipes-python/qt5/files/py3qterm-0.4/debian/changelog
meta-isar/recipes-python/qt5/files/py3qterm-0.4/debian/control
meta-isar/recipes-python/zerorpc/files/zerorpc-0.6.3/debian/changelog
meta-isar/recipes-python/zerorpc/files/zerorpc-0.6.3/debian/control

Resolved do_install_builddeps failures when building against Isar v0.8-rc1 by having Python packages Build-Depend on python3-all-dev
Note: the actual switch to Isar version 0.8 is deferred to v0.16

Prepare for Isar 0.8

---

configs/qemu.ini
docs/config.rst
mtda/power/qemu.py

Support emulation of multiple system drives with "storage.<N>"
configuration entries. If both "storage" and "storage.0" are
set, "storage.0" will be used.
Fixes: #161

power/qemu: support additional system drives

---

configs/qemu.ini
docs/config.rst
mtda/power/qemu.py

Provide QEMU configuration for the number of cores
Signed-off-by: Gunther Birk <gunther.birk@siemens.com>

Qemu configuration for multiple cores

---

mtda/main.py

Put test fixture like power controller or storage muxes into a known
state when MTDA is started.

main: start with board off and storage on target

---

mtda/power/docker.py

Docker's images.pull() defaults to all_tags=False. There are
however reports that MTDA would fetch all images on start-up.
Call pull() with all_tags explicitly set to False.

power/docker: make sure we do not pull all images

---

mtda/power/docker.py

python3-docker < 4.4.0 pulls all tags by default.
Explicitly pass the tag to fetch to fix the issue.
This solution should work with the python3-docker > 4.4.0 as well.
Ref: https://github.com/docker/docker-py/commit/daa9f179c3a3e666c0b2cbccebd88756bc30d058
Fixes the below commit
70c0a67bf28f72de92525bfb4bd4c9f89b28013e
Reported-by: Onkar Bokshe <OnkarSurendrakumar_Bokshe@mentor.com>

power/docker: Fix pulling all tags

---

docs/config.rst
mtda.ini
mtda/console/logger.py
mtda/constants.py
mtda/main.py
mtda/templates/index.html
mtda/www.py
setup.py

Make ConsoleLogger send output to a Flask-SocketIO socket that may
be consumed by an xterm.js-based terminal in the browser.
Closes: #184

www: allow remote access to the console via web browsers

---

meta-isar/recipes-core/images/mtda-image.inc

Resolves the related warning and delivers the required information to
/etc/os-release.
BTW, you likely also want to stop using the exemplary isar-image-base or at least set an own image DESCRIPTION.

meta-isar/recipes-core: Initialize ISAR_RELEASE_CMD

---

mtda/storage/qemu.py

A backing file should be created using the default name when a
custom 'file' isn't specified in the configuration.
Fixes: 3da7a12

storage/qemu: create backing file when 'file' is not set

---

.github/workflows/main.yml
kas/common/base.yml
kas/debian/mtda-nanopi-all.yml
meta-isar/recipes-core/images/isar-image-base.bbappend
meta-isar/recipes-core/images/mtda-image.bb

Create our own variation of image called mtda-image.
Closes: #210

meta-isar: create our own target image

---

mtda-cli

Clients should always connect to the daemon/service. Assume "localhost"
when no remote is specified on the command line instead of silently
failing.
Closes: #219

mtda-cli: use 'localhost' as default remote

---

meta-isar/conf/machine/nanopi-r1.conf
meta-isar/recipes-bsp/u-boot-script/u-boot-script_%.bbappend
meta-isar/recipes-core/images/mtda-image.bb

u-boot-script ships /etc/default/u-boot-script where some machine
specific settings are placed (such as the kernel command line).
Add DISTRO and MACHINE to the name of the package to get separate
binary packages for the machines we support in our package feeds.

meta-isar/recipes-bsp: suffix u-boot-script with DISTRO and MACHINE

---

mtda/console/input.py

Some distros still use this, at least SUSE/SLES.
There might be more issues, but at least basic functionality of mtda-cli is working fine under SUSE 15.3 here so far.

console/input: Restore Python 3.6 compatibility

---

mtda/console/logger.py

The there is no power controller, assume that the device is already
powered. Without this, the console does not work in most cases.
Keeping the suspicious locking pattern untouched for now, that one is
likely broken as well.
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

console/logger: Open console unconditionally

---

meta-isar/recipes-python/mtda/mtda_git.bb

This avoids pulling random versions from github, permitting to package
local changes as well as clearly defined releases. The price is the need
of maintaining a list of top-level files and directories.
As the resulting input for the package build is now a local folder, the
source/format used for the Isar build needs to be switched to default.
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

meta-isar/recipes-python: Build local version

---

docs/config.rst
mtda/power/shellcmd.py

This driver allows to manage power switches via simple shell commands.
It is a break-out box for a broad range of bindings, e.g. by using curl
to talk to the REST interface of a power control.
Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>

power: Add shellcmd driver

---

mtda/storage/usbf.py

This allows to replace the backing file while it is in host mode and
informs the USB gadget about changes to it. Also, the target will not be
able to access it anymore while it is in host mode.
Maybe it is possible to further automate updates by unconditionally reinstalling the device on target power-on.

storage/usbf: Remove and re-install storage when switching between host and target

---

setup.py

zerorpc fails with errors such as 'zerorpc.gevent_zmq' has no attribute
'PUSH' when running against the latest version. Changes to zerorpc are
probably required.
Closes: #242

setup: require pyzmq<23.0.0

---

meta-isar/recipes-python/zerorpc/files/0001-gevent_zmq-import-enums-from-pyzmq-23.0.0.patch
meta-isar/recipes-python/zerorpc/files/zerorpc-0.6.3/debian/changelog
meta-isar/recipes-python/zerorpc/zerorpc-python_0.6.3.bb

Pull zerorpc-python submitted upstream (see issue #251) for 0.6.3 to
be compatible with pyzmq 23.0.0
Fixes: #242

meta-isar/recipes-python: make zerorpc-python work with pyzmq 23.0.0

---

docs/config.rst
meta-isar/recipes-core/images/mtda-image.bb
mtda/power/gpio.py
mtda/usb/gpio.py

Since linux kernel v4.8 the GPIO Sysfs ABI is deprecated[1]. This
commit replaces the existing gpio controls which uses sysfs with
the new GPIO Char Device API(libgpiod).
A new 'gpiochip' property is now required when using 'gpio' variant
for power.
[1] (https://www.kernel.org/doc/Documentation/gpio/sysfs.txt)

Gpio sysfs to libgpiod

---

configs/qemu.ini
debian/rules
mtda/main.py
mtda/scripts/__init__.py
mtda/scripts/ipc227e.py
mtda/scripts/qemu.py
setup.py
tox.ini

Ease sharing of device scripts that are used to boot from USB, reset the TPM, enable Secure Boot, etc. by having MTDA load them from mtda.script.<variant> with <variant> being loaded from the [environment] section of the configuration file. Sample scripts for the Siemens SIMATIC IPC227E are provided with this changeset.

scripts: add support for loading device scripts

---

meta-isar/conf/layer.conf
meta-isar/recipes-core/images/mtda-image.bb

Gemfury now supports signed apt repositories, add the project GPG key to the 3rd-party keyring and remove [trusted=yes] from mtda.list

meta-isar: images: add GPG key to the apt keyring

---

docs/build.rst

ISAR generates an image without .img extension.

docs/build: remove .img from ISAR image name

---

docs/build.rst

Fix of the example configuration documentation for the NanoPi, which isn't adopted to the libgpiod style yet.

docs/build: power configuration example adapted to libgpiod

---

mtda-cli

mtda-cli may be either used in client or server mode but not
both. Reject use of -d and -r options together.
Signed-off-by: Shivaschandra KL <shivaschandra.k-l@siemens.com>

mtda-cli: prohibit user from daemonizing client

---

debian/changelog

The last couple of entries in the debian changelog had the wrong year.

debian: changelog date typo fix

---

.github/workflows/main.yml
.github/workflows/pypi.yml
.github/workflows/ubuntu.yml

Avoid NodeJS 12 deprecation warnings by using v3 of the checkout action.

ci: upgrade actions/checkout from v2 to v3

---

docs/config.rst

Minor spelling fixes in docs/config.rst

docs/config: fix spelling

---

mtda/storage/controller.py
mtda/storage/helpers/image.py
mtda/storage/writer.py

Some decompressors may perform writes in the background and/or after the final call to write(). Add tell() to the storage interface to report the current position within the storage instead of calculating it from the some of return values from write(). This fixes the issue of no progress being shown after a zst stream was consumed.

mtda: use tell() to report how many writes were completed

---

mtda-cli

From 3eee065. mtda server code is moved to mtda-service.
Cleanup mtda-cli to remove stale references to daemon code.
Fixes: 3eee065

mtda-cli: cleanup stale code

---

meta-isar/conf/layer.conf

The layerdir variable contains an absolute path that is immediately expanded and points into the build host. This breaks sstate caching for tasks that reference this variable when building from a different path (like in the gitlab-ci). To fix this, we simply set the vardepvalue to a fixed value. As this variable just points to the current layer, there are no logical external changes expected and by that, this "pinning" is fine.

improve caching of mtda isar layer

---

.reuse/dep5
mtda/assets/material_icons.css
mtda/assets/vnc.js
mtda/share/nginx-multi-mtda.conf
mtda/templates/index.html

This change ensures that all resources are references relative to the
current URI. By that, the whole MTDA web frontend can be served below a
subpath. This is required to support use-cases where multiple MTDA
devices are served by a single nginx reverse proxy in a single web page.
This approach can be used to serve a whole testing network via a single
IP entrypoint and without giving the users IP access to the testing
network itself.
To make the socket.io communication work, we further set the path
component of the current URI when connecting to the ws server.

Add support to run MTDA web frontend behind reverse proxy

---

meta-isar/recipes-core/images/mtda-image.bb
mtda/assets/vnc.js
mtda/templates/index.html

Firstly the mtda-www package is added to the image. This is done because installing it manually afterwards with `sudo apt install mtda-www` from the fury repository installs it for python 3.9. and not the 3.11. version for bookworm.
Also, since the choice of using the webview comes from the configuration files anyway, it should not interfere.
Secondly, referring to #300, the `mtda/templates/index.html` and `mtda/assets/vnc.js` was changed to work with the newer novnc-package which is used in debian bookworm(https://packages.debian.org/bookworm/all/novnc/filelist). 
Consider that this will break the web-view for all mtda-images which are still built with bullseye.

Add mtda-www to image and fix web-ui console for bookworm

---

.github/workflows/main.yml

Isar is now using .wic as suffix for wic images (was .wic.img in earlier versions).

ci: correct path to wic images

---

mtda/main.py

Move os.getenv('MTDA_REMOTE') so that it gets called when mtda-cli is loaded without any configuration files.
Fixes: #298

main: load MTDA_REMOTE from the environment even without config files

---

docs/build.rst

Since a backing file/device is required for the emulated storage to work, let's make sure setup instructions for the NanoPI NEO have "file" set to "/dev/sda" to make sure people end-up with something that works out of the box.
Fixes: #296

docs/build: add "file" setting to the [storage] section

---

mtda/client.py
mtda/main.py
mtda/storage/controller.py
mtda/storage/helpers/image.py

This update addresses issue #15.
Since the class `BmapBdevCopy` from the `bmaptools`  package expects a file stream to work properly and in this implementation we work with chunks of data, a custom algorithm for writing bmap 2.0 images is created.
In `client.py` a bmap file in the same folder as the image supplied with `mtda-cli storage write image.wic` is searched. If there is no .bmap  or the parsing of the .bmap file goes wrong, the image is written just like before. The algorithm was tested with 2 different images with holes. Each currently supported format (raw, bz, gz, xz and zst) was used for both of them and successfully flashed to a storage.
Credits go also to @fmoessbauer for supporting this endeavor.

Added algorithm to auto-parse .bmap 2.0 files and write accordingly

---

mtda/storage/helpers/image.py

Before writing a new image file, we need to reset the internal state of the bmap writing algorithm. Otherwise subsequent writes do not start with a clean state. While fixing this, we also shink the state by making the number of written blocks a local variable (it can be trivially computed from the bytes written and the blocksize).
Hopefully that's the last fix for the bmap algorithm. Unfortunately all that is not easy to test, because many of the issues only show up on big and more complex images.

fix(bmap): reset internal state before writing

---

docs/config.rst
mtda/storage/samsung.py

The serial of the sdwire interface depends on the physical device it is attached to. This makes it impossible to pre-configure multiple MTDA devices for a mass deployment.
This patch auto-detects the serial of an sdwire in case it is not specified in the configuration. This simplifies the default configuration and also enables pre-configuration of MTDA devices.
Note: This has been tested on multiple nanopi-neo boards with sdwire interfaces.
cc @bovi

feat: auto-detect serial interface of sdwire

---

mtda-service

register_service() may raise NonUniqueNameException if a device with the same name (defaulting to the static hostname, i.e. /etc/hostname) is already on the network. Do not die if that happens and simply disable Zeroconf.
Fixes: #329

mtda-service: do not die if ZeroConf fails to register the service

---

mtda/power/qemu.py

The -watchdog option is deprecated, -device <watchdog-driver> should be used instead moving forward.

power: qemu: use -device option to instantiate the watchdog driver

---

mtda/client.py

When using the mtda client API, a user might want to work with much shorter timeouts when connecting to remote devices. This patch makes this timeout configurable and also adds some (limited) documentation of the Client constructor.
cc @bovi

feat(mtda-client): make timeout configurable

---

kas/common/base.yml

The main (and only?) driver for this update is to remain up-to-date with the isar project.

kas: update to the latest HEAD of the isar tree

---

mtda/share/nginx-multi-mtda.conf
mtda/templates/index.html

This patch adds support to also serve the mjpeg streamer endpoint via a reverse proxy. The reverse proxy is auto-detected based on a heuristic (access path starts with /device). The example nginx reverse proxy configuration is updated accordingly.
cc @bovi

feat(www): support mjpeg streamer via reverse proxy

---

mtda/client.py

When using RPC timeouts shorter than the heartbeat value, the timeout of the RPC call was not properly working, as the call only returned after the heartbeat duration. In normal operation, this was not an issue, as the heartbeat was significantly shorter than the timeout, and also timeouts only happened due to function invocation timeouts, but not due to connectivity losses.
When working with one-shot RPCs (i.e. create a client to only call one rpc), this led to huge delays and an accumulation of half-open TCP connections. By clamping (limiting) the heartbeat duration to the timeout, also short timeouts are properly supported now.

fix(client): clamp heartbeat to timeout value

---

docs/config.rst
meta-isar/recipes-core/images/mtda-image.bb
mtda.ini
mtda/templates/index.html
mtda/video/mjpg_streamer.py
mtda/video/ustreamer.py

For now, we support both mjpg_streamer and ustreamer, but the plan is to eventually deprecate mjpg_streamer. This has been successfully tested with some screen grabbers and cameras, but more testing should be done. Anyways, I'll already provide the patches so more folks can help with the review and testing.
It also uses a more "modern" approach to run the streamer in the background.
cc @bovi

Add support for streaming via ustreamer

---

debian/mtda.udev
mtda/console/serial.py
mtda/storage/usbf.py
mtda/utils.py
mtda/video/mjpg_streamer.py
mtda/video/ustreamer.py

This is another try at fixing the systemd unit dependency to the screen grabber. It is based on #349, but only uses the udev part. It has been tested on an nanopi-neo with a USB3 screen grabber attached.
cc @bovi

fix(video): avoid timeout during check for v4l2 device | v2

---

meta-isar/recipes-python/mtda/mtda_git.bb

Some packages we currently build locally are already available in debian bookworm. By using these, we automatically get security updates and also reduce the build time of the mtda images. This reduces the build time of the debian bookworm images by more than 10 minutes.
cc @bovi

refactor(mtda): use upstream packages on bookworm

---

.github/workflows/assign.yml
.github/workflows/pypi.yml

Fixes ci job warning:
The following actions uses node12 which is deprecated and will be forced to run on node16
Auto assign release: https://github.com/kentaro-m/auto-assign-action/releases
Setup python release: https://github.com/actions/setup-python/releases

ci: bump auto-assign-action and setup-python versions

---

docs/install.rst

Fixes GPG warning observed while performing 'apt update' operation:
GPG error: https://apt.fury.io/mtda  InRelease: The following signatures couldn't be verified because the public key is not available
Signed-off-by: Badrikesh Prusty <badrikesh.prusty@siemens.com>
Apt warning observed:
```
badrikesh@debian:~$ sudo apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://deb.debian.org/debian bookworm-backports InRelease
Get:5 https://apt.fury.io/mtda  InRelease [1,975 B]
Ign:5 https://apt.fury.io/mtda  InRelease
Get:6 https://apt.fury.io/mtda  Packages [228 kB]
Fetched 230 kB in 3s (87.6 kB/s)
Reading package lists... Done
Building …
```

docs/install.rst: do GPG key setup before setting sources for debian

---

meta-isar/recipes-conf/mtda-repo/files/postinst.tmpl

- Source list apt-get test:
```
mtda@mtda:~$ cat /etc/apt/sources.list.d/mtda.list
deb https://apt.fury.io/mtda/ * *
mtda@mtda:~$
mtda@mtda:~$ sudo apt update
[sudo] password for mtda:
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:4 https://apt.fury.io/mtda * InRelease
Get:5 http://deb.debian.org/debian-security bookworm-security/main Sources [52.1 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main armhf Packages [82.0 kB]
Get:7 http://deb.debian.org/debian-security bookworm-security/main Translation-en [49.2 kB]
Fetched 290 kB in 10s (29.4 kB/s)
Reading package lists... Done
Building dependency tree... …
```

recipes-conf/mtda-repo: append source list with ' /' (vs ' * *')

---

.github/workflows/main.yml

Fixes 'Build kas/ci targets' job warnings:
The following actions uses node12 which is deprecated for 'upload-artifact' action

ci: bump actions/upload-artifact version to v3

---

debian/control
docs/usage.rst
mtda/client.py
mtda/storage/writer.py

The 'storage write' command may now download an image (and its associated .bmap file if it exists) from an S3 bucket. Credentials may be provided in the environment (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY).

client: support 'storage write' from an S3 bucket

---

mtda-cli
mtda/client.py
mtda/main.py
mtda/storage/helpers/image.py

Raise and propage exceptions when the shared storage cannot be opened or when a write error occurs instead of returning False. Exceptions raised over ZeroRPC become RemoteError exceptions and the msg attribute holds a human-readable error message.

storage: use exceptions for open/write instead of booleans

---

mtda/client.py
mtda/main.py

The storage_update need to change since the _storage_write is removed.
to solve issue #366 
cc @chombourger  @bovi

storage: fix storage_update API

---

mtda/client.py
mtda/main.py
mtda/storage/helpers/image.py
mtda/storage/writer.py

```sh
1. mtda-cli -r  $HOST_NAME storage write  1.0.1-installer.wic.xz
2. mtda-cli -r $HOST_NAME storage mount 3
3. mtda-cli -r $HOST_NAME storage update $image_path_in_installer.bmap $bmap_path
4. mtda-cli -r $HOST_NAME storage update $image_path_in_installer.xz $xz_path
5. mtda-cli -r  $HOST_NAME storage target
6. mtda-cli -r  $HOST_NAME target on
7. ...
8. mtda-cli -r  $HOST_NAME target off
9. mtda-cli -r  $HOST_NAME storage host
10. mtda-cli -r  $HOST_NAME storage write  1.0.2-installer.wic.xz
11. mtda-cli -r $HOST_NAME storage mount 3
```
When I run a shell script like above, I found some trick bugs: 
- The 1st commit to fix #267 **  . 
I encountered the same error sometimes and the error message is just like this issue. 
So the error in #267  means that there are still  many data to …

fix some tricky bugs by setting flags at the proper timing and place

---

mtda/client.py

The refactoring in 0ccb5c6 always called the image write status reporting callback without a precise image size, even if that was available (e.g. from the bmap file). This commit restores the old behavior and passes the precise size information to the callback if available.

fix: use exact output size in clbk if available

---

mtda/power/usbrelay.py

The usbrelay command is async, hence we cannot immediately after changing the state check if it became active. Instead, we need to poll for some time and report back either if the state changed, or on timeout. To leave sufficent time for other parts of the code, we check until half of the RPC timeout is expired.

fix(usbrelay): poll for status to confirm

---

mtda/constants.py
mtda/main.py
mtda/power/docker.py
mtda/templates/index.html

Tell user interface(s) when storage gets locked/unlocked to enable or disable the storage swap button they may provide. Such events are triggered from power on/off and storage open/close operations.

feat(main): emit storage locked/unlocked events

---

mtda/keyboard/hid.py
mtda/main.py

The hid keyboard driver understands <esc>, <left>, <right>, <down>, <up> and function keys as special keys. Move this handling in main for other drivers (such as qemu) to also handle these special keys as users of keyboard.write() may reasonably expect.

chore(keyboard): handle special keys in main

---

.github/wordlist.txt
docs/config.rst
mtda/storage/usbf.py

When a file is used as backing store for the shared storage, create a loopback device to make sure writes are contained within the limits of the file.

chore(usbf): create a loopback device when a file is used

---

mtda/power/qemu.py

Attempt to write to the FIFO for QEMU's monitor may block. Simplify shutting down of qemu/kvm by removing the use of the "quit" command and immediately send SIGTERM.

chore(power/qemu): simplify shutdown

---

debian/mtda-service.postinst

debian: do not call mtda-systemd-helper when running in chroot

---

.github/wordlist.txt
docs/integration.rst
kas/opt/lava.yml
meta-isar/recipes-core/images/mtda-image.bb

meta-isar: images: make LAVA an optional feature

---

Kconfig
docs/config.rst
meta-isar/recipes-core/images/mtda-image.bb
mtda.ini
mtda/storage/qemu.py
mtda/storage/usbsdmux.py

See patch 1 for details.
@fmoessbauer

Add usbsdmux support

---

docs/config.rst
mtda.ini
mtda/power/gpio.py

Introduce an optional `enable` config key for the power gpio. This config defaults to `high` for high level triggered relays but can be set to `low` for low level triggered relays.

power/gpio: Allow to configure low level triggered relays

---

mtda/templates/index.html

The default browser keyboard actions interfere with the keyboard based interaction with the device. Disable them for the MTDA web interface.

fix(www): Disable browser shortcuts

---

mtda/assets/keysight.js
mtda/keyboard/controller.py
mtda/keyboard/hid.py
mtda/keyboard/qemu.py
mtda/templates/index.html
mtda/www.py
tox.ini

Expose a press function in the keyboard controller that handles the press of a single key with modifier keys. Use this function from the web UI to allow to hit key combinations like ctrl-c.
Can please somebody test this with qemu? I do not have a running qemu setup atm.

feat(www): Enable the usage of modifier keys

---

kas/common/base.yml
meta-isar/recipes-bsp/rpi-firmware/files/rules
meta-isar/recipes-crypto/gnutls/gnutls28.bb

- Update to latest ISAR revision
- Use SRC_APT for apt packages (vs SRC_URI). Here, for gnutls package.
- Rpi-firmware: Consists of .elf binary files
Avoid striping it or strip dwarf debug information
Fixes build failure
Nano pi build and boot tested:
Nanopi neo booting fine. Boot logs:
[mtda-latest-isar.txt](https://github.com/siemens/mtda/files/14540227/mtda-latest-isar.txt)

kas/common/base: update isar to latest revision

---

.github/wordlist.txt
Kconfig
docs/config.rst
mtda.ini
mtda/power/anel.py

Anel sells several different ethernet power strips. https://en.anel.eu/ The strips expose a UDP api that allows to switch the plugs on and off. Add a simple power driver for this UDP interface.

feat(power): add driver for Anel ethernet power strips

---

.github/workflows/assign.yml
.github/workflows/main.yml
.github/workflows/pypi.yml
.github/workflows/spellcheck.yml

Update github actions to:
- kentaro-m/auto-assign-action: 2.0.0
- actions/checkout: 4
- actions/cache: 4
- actions/upload-artifact: 4
- actions/setup-python: 5
- crazy-max/ghaction-import-gpg: 6
- rojopolis/spellcheck-github-actions: v0
Fixes: Warnings: Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

ci: update actions to latest version and fix nodejs deprecated warning

---

kas/common/base.yml

- Enable Compiler cache for the builds
- It reduces build time during recompilation by caching previous compilations, and detecting when same compilation is being done again
- Tested nanopi neo image build time got reduced by 5 minutes
Build tests:
```
Without ccache:
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |######################################################################################################################################################################################################| Time: 0:00:00
Parsing of 76 .bb files complete (0 cached, 76 parsed). 128 targets, 15 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |########################################################################### …
```

kas/common/base.yml: enable use of ccache for the builds

---

mtda/main.py
mtda/storage/writer.py

Found while reading/refactoring the related code sections.

Smaller cleanups/fixes

---

mtda/client.py

When copying an uncompressed image, we lightly compress the image on the fly with zstd on transfer. By that, subsequent zeros (holes) are automatically collapsed and not transferred, which can give a huge speedup on uncompressed images. Another advantage is, that zstandard can be decompressed with a very low overhead (e.g. compared to gz or xz) and is better suited for low-memory devices.
closes: #20

When copying uncompressed images, compress on them on-the-fly

---

.github/workflows/assign.yml

Explicitely stating required permissions is considered best practice.
This case was detected by Poutine, see
https://github.com/boostsecurityio/poutine/blob/main/docs/content/en/rules/default_permissions_on_risky_events.md.
Signed-off-by: Florian Greinacher <florian.greinacher@siemens.com>

ci(assign): define permissions for auto assign workflow

---

meta-isar/recipes-python/compression/python-zstandard/debian-compat.patch
meta-isar/recipes-python/compression/python-zstandard_0.22.0.bb

New upstream release 0.22.0
Test logs:
```
bp@ipc847e:~/zstandard/mtda$ ./kas-container build kas/ubuntu/mtda-qemu-amd64.yml
2024-06-26 16:12:50 - INFO     - kas 4.3.1 started
2024-06-26 16:12:50 - INFO     - Using /repo as root for repository mtda
2024-06-26 16:12:50 - INFO     - Repository isar already contains ac9b9031fcaad47b7163598924198954f6523e3f as commit
2024-06-26 16:12:50 - INFO     - Repository isar checked out to ac9b9031fcaad47b7163598924198954f6523e3f
2024-06-26 16:12:50 - INFO     - /build$ /work/isar/bitbake/bin/bitbake -c build mtda-image
Loading cache: 100% |                                                                                                                                                                            | ETA:  --:--:--
Loaded 0 entries from …
```

meta-isar/recipes-python: upgrade python-zstandard to 0.22.0

---

mtda/client.py
mtda/constants.py

If the client writes data too quickly, the agent may see its input queue full. Give ourselves up to 30 seconds to submit the data to be written to the shared storage before giving up.

fix(storage): add retry mechanism to recover from a full input queue

---

mtda/power/anel.py

result is unbound if _receive times out with the follow exeception:
mtda-mcom mtda-service[1400]:     self._switch(False)
mtda-mcom mtda-service[1400]:   File "/usr/lib/python3.11/dist-packages/mtda/power/anel.py", line 88, in _switch
mtda-mcom mtda-service[1400]:     if result == "0":
mtda-mcom mtda-service[1400]:        ^^^^^^
mtda-mcom mtda-service[1400]: UnboundLocalError: cannot access local variable 'result' where it is not associated with a value

fix: anel.py declare result in front of exception

---

kas/common/base.yml

The version of Isar we were on is trying to forcibly install the usrmerge package while it was removed in Ubuntu Noble. This was fixed upstream in the next branch: switched to it for the time being.
See: https://groups.google.com/g/isar-users/c/c_d8103JlRY

fix(build): switch to isar next to fix ubuntu noble builds

---

docs/install.rst

The installation documentation needs to be updated to use the correct
configuration file names for the Docker and KVM virtual platforms.
The configuration files are now named mtda.ini instead of docker.ini
and qemu.ini, respectively.

fix(docs): update config file name in install docs

---

debian/mtda-client.postinst
debian/mtda-client.sudoers
debian/rules
mtda/client.py

Ship some sudoers rules to let users belonging to the "mtda" group attach a network block device without a password.

feat(storage): no longer require a password when spawning nbd-client

---

mtda/pytest.py

Target is our pytest module expects the image specified in the TEST_IMAGE environment variable (or its default value) to exist. No longer fail if an image is not specified in the environment and if the default one could not be found: this may be intented.

fix(pytest): do not fail if the default TEST_IMAGE cannot be found

---

mtda/main.py

While installing mtda .deb package on Debian 12 host, observed following traceback
```
Setting up mtda-service (0.36-0) ...
Traceback (most recent call last):
File "/usr/sbin/mtda-systemd-helper", line 67, in <module>
sys.exit(app.main())
^^^^^^^^^^
File "/usr/sbin/mtda-systemd-helper", line 57, in main
self.agent.systemd_configure()
File "/usr/lib/python3.11/dist-packages/mtda/main.py", line 973, in systemd_configure
self.systemd_configure_www()
File "/usr/lib/python3.11/dist-packages/mtda/main.py", line 1020, in systemd_configure_www
shutil.rmtree(etcdir)
File "/usr/lib/python3.11/shutil.py", line 722, in rmtree
onerror(os.lstat, path, sys.exc_info())
File "/usr/lib/python3.11/shutil.py", line 720, in rmtree
orig_st = os.lstat(path, dir_fd=dir_fd)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

fix(main): remove etcdir if only exists

---

mtda/main.py

storage_mount() did not check/update storage_owner

fix(storage): session should own the storage after mounting

---

mtda/client.py
mtda/main.py
mtda/storage/docker.py
mtda/storage/helpers/image.py

When storage write was modified to use zmq, storage update should have been modified as well.

fix(storage): make update also use zmq

---

debian/mtda-service.postinst
meta-isar/recipes-core/images/mtda-image.bb

For details, see individual commit messages.

Fix mtda user creation and lava dropin

---

meta-isar/conf/machine/rpi4b.conf
meta-isar/recipes-bsp/rpi-firmware/rpi-firmware_1.20250305.bb
meta-isar/scripts/lib/wic/canned-wks/rpi4b.wks

For details, see the commit messages.
Unfortunately for kernels < 6.5 we still can't use the DTB overlays, as the device tree of the `bcm2711-rpi*` targets does not contain the symbol information.

A couple of improvements for the RPI4b target

---

meta-isar/conf/machine/rpi4b-efi.conf
meta-isar/recipes-bsp/rpi-firmware/files/debian/rpi-firmware.install

These overlays somehow got lost during rebasing. We need them as otherwise the target does not boot.
Fixes: 41e6584 ("feat(rpi4): add target to support EFI booting")

fix(rpi4): add overlays needed for efi booting

---

mtda-cli
mtda/client.py

While doing so, I noticed that many commands are broken. For `console_toggle` and `target_lock` the fix is trivial, but for the others (like `storage_swap`) it needs to be fixed in the attr-injector. I'm anyways wondering if the session should be manually injected or if the attr-injector should handle this.

feat: add key to print help message

---

.reuse/dep5
meta-isar-extra/conf/machine/abrootfs-common.inc
meta-isar-extra/recipes-conf/swupdate-config-wfx/files/wfx.conf.tmpl
meta-isar-extra/recipes-conf/swupdate-config-wfx/swupdate-config-wfx_0.1.bb
meta-isar-extra/recipes-core/images/mtda-image-immutable.bb

We add a swupdate configuration to update the device with one of the DAU workflows from WFX. The WFX server can be specified with the WFX_SERVER bitbake variable (e.g. via a kas local config) and defaults to http://localhost:8080. By that, local tests with a SSH reverse forward can be done.
Once we have the general A/B rootfs image documented, we should also add example snippets to run the WFX workflow. But that's really just the example from https://siemens.github.io/wfx/docs/workflows/dau/

Integrate swupdate with WFX

---

mtda/main.py

This method is called with the auto-injected session parameter. While the session is irrelevant for this function, we must be interface compatible.
Fixes: fae44dc ("refactor(client): use dynamic wrappers for remote ...")

fix: add kwargs to toggle_timestamps method

---

mtda/storage/helpers/image.py

There was a subtle blug in our implementation of the bmap algorithm: When ending a range but still carying an overlap (a not fully written block), the next overlap is computed was computed incorrectly. By that, the writing position shifted by [0-blocksize) bytes which lead to incorrectly written data blocks. This was detected by a checksum mismatch.
We fix this by further simplifying the algorithm: Instead of computing the overlap based on a delta, we simply compute it by taking "writtenBytes % blocksize". We did this anyway in case the current input was fully processed, now we also do it within the block writing logic.
Xref: #476 (failure is still not reported, but the bug in writing is fixed).
Please review carefully and also test on some files.

fix(image): correctly handle range end with overlap

---

meta-isar/conf/machine/rpi4b-efi.inc

We cannot define the WKS_FILE and IMAGE_FSTYPES as extra weak variables as isar/meta/classes/imagetypes_wic.bbclass also has an extra weak define which is loaded earlier. To fix this, we switch to weak defines.
Fixes: 46b2f6a ("refactor(rpi4): carve out common efi firmware part")

fix: use correct wks file on rpi4b-efi target

---

mtda/client.py
mtda/storage/writer.py

In case the storage write is interrupted (e.g. because of a checksum mismatch or another internal error), we need to inform the other side about the issue.
As the current architecture does not provide an easy mechanism to inform about this, we just check if the written bytes are equal to the expected ones (in case we know about the full size.
Closes: #476

client: check if image is fully written

---

debian/control
docs/config.rst
mtda/network/usbf.py

Let the agent forward traffic received on designated ports to the Device Under Test (which may be connected on a separate/isolated network).

feat(network): add NAT forwarding

---

meta-isar/conf/distro/preferences.mtda-bookworm-backports.conf

linux-image-* packages from -backports depend on linux-base >= 4.12 while bookworm ships 4.9. Let us pull linux-base from -backports for dependencies to be met.
Fixes: 1d3c93a

fix(packages): linux-image-* from bpo now depends on linux-base

---

mtda-cli
mtda/main.py
mtda/storage/writer.py

When writing compressed images, a few reads may results in many writes: get progress updates from the event channel rather than client-side reads (via the progress callback).

perf(cli): use event channel for "storage write" progress updates

---

mtda-www
mtda/templates/index.html

Physical Keyboard Failed to send the space in mtda-www. Added fix to send the modified strings for space and added downstream API to handle space. Before the change downstream API was unable to detect space and was sending empty string.

fix(keyboard): fix space key issue in www

---

mtda/templates/index.html

Specify a minimum size for our video window and make the <img> used for the video feed use a width and height of 100%.

fix(www): make the video stream fit its window without scrollbars

---

mtda/templates/index.html

As we may have multiple windows opened (console, python, video), we want key presses to be sent to the Device Under Test only when the video window is focused.

fix(www): check if the video window is focused to process keydown events

---

mtda/assets/www.py
mtda/pytest.py

Console.wait_for() would sleep before checking for matches or errors: this is not necessary and should be done at the end of the retry loop

perf(pytest): make Console.wait_for() sleep after checking for matches

---

kas/ci/fast.yml
kas/ci/full.yml
kas/common/base.yml
kas/debian/bookworm-base.yml
kas/debian/mtda-beaglebone-black.yml
kas/debian/mtda-nanopi-neo-ebg.yml
kas/debian/mtda-nanopi-neo.yml
kas/debian/mtda-qemu-amd64-ebg.yml
kas/debian/mtda-qemu-amd64.yml
kas/debian/mtda-rpi4b-ebg.yml
kas/debian/mtda-rpi4b-efi.yml
kas/debian/mtda-rpi4b.yml

The config/base fragment defines a default target. That was fine until we wanted to build using
kas/debian/mtda-rpi4b-ebg.yml:kas/debian/trixie-base.yml
The debian/trixie-base fragment would override the non-default target "mtda-immutable-image" but that change would be lost with debian/trixie-base since it would include again common/base.
Targets should include both common/base and debian/*-base
Suggested-by: Felix Moessbauer <felix.moessbauer@siemens.com>

fix(kas): debian/bookworm-base should not include common/base

---

.github/workflows/main.yml
scripts/build-using-ppa

reduce our storage requirements for our CI builds by removing build/tmp/work after each build. We however keep build/tmp/deploy for artefacts we may want to archive.

ci: remove build/tmp/work after each build

---

configs/qemu.ini

Use /usr/share/ovmf/OVMF.fd since found in both bookworm and trixie while /usr/share/OVMF/OVMF_CODE.fd only exists in bookworm.

fix(configs): use /usr/share/ovmf/OVMF.fd for bookworm and trixie
